name: build-js-sass
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
jobs:
  main:
    name: Build and lint js & sass
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: anirbanshaw24/r-setup-action@v2

      - name: Lint JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::lint_js()

      - name: Build JavaScript
        if: always()
        shell: Rscript {0}
        run: rhino::build_js()

      - name: Lint Sass
        if: always()
        shell: Rscript {0}
        run: rhino::lint_sass()

      - name: Build Sass
        if: always()
        shell: Rscript {0}
        run: rhino::build_sass()
