name: r-unit-test-lint
on:
  push:
    branches:
      - "main"
permissions:
  contents: read
jobs:
  main:
    name: Unit test & lint R
    runs-on: ubuntu-22.04
    steps:
      - name: Setup environment
        uses: anirbanshaw24/r-setup-action@v2

      - name: Lint R
        if: always()
        shell: Rscript {0}
        run: rhino::lint_r()

      - name: Run R unit tests
        if: always()
        shell: Rscript {0}
        run: rhino::test_r()
